# Generated by Django 2.1.7 on 2019-03-22 11:27

from django.db import migrations, models

from common.constants import Messages as CommonMessages, MessageTypes
from authentication.constants import Messages as AuthenticationMessages
from profiles.constants import Messages as ProfilesMessages


def forward_function(apps, schema_editor):
    # Create message objects
    _Message = apps.get_model('common', 'Message')

    _Message.objects.create(key=CommonMessages.UNHANDLED_ERROR,
                            type=MessageTypes.ERROR,
                            body='Unhandled error.', )
    _Message.objects.create(key=CommonMessages.REQUEST_PARAMETER_MISSING,
                            type=MessageTypes.ERROR,
                            body='Request parameter missing.',)
    _Message.objects.create(key=CommonMessages.REQUEST_PARAMETER_INVALID,
                            type=MessageTypes.ERROR,
                            body='Request parameter invalid.', )
    _Message.objects.create(key=CommonMessages.HEADER_PARAMETER_MISSING,
                            type=MessageTypes.ERROR,
                            body='Header parameter missing.', )
    _Message.objects.create(key=AuthenticationMessages.TOKEN__AUTHENTICATION_FAILED,
                            type=MessageTypes.ERROR,
                            body='Authentication failed.', )
    _Message.objects.create(key=AuthenticationMessages.TOKEN__LOGOUT_SUCCESS,
                            type=MessageTypes.SUCCESS,
                            body='Successfully logged out.', )
    _Message.objects.create(key=AuthenticationMessages.TOKEN__INVALID,
                            type=MessageTypes.ERROR,
                            body='Token invalid.', )
    _Message.objects.create(key=AuthenticationMessages.TOKEN__PERMISSION_DENIED,
                            type=MessageTypes.ERROR,
                            body='Permission denied.', )
    _Message.objects.create(key=ProfilesMessages.USER__PASSWORD_MISSING,
                            type=MessageTypes.ERROR,
                            body='Please provide both password fields.', )
    _Message.objects.create(key=ProfilesMessages.USER__PASSWORDS_DO_NOT_MATCH,
                            type=MessageTypes.ERROR,
                            body='Passwords do not match.', )
    _Message.objects.create(key=ProfilesMessages.USER__INVALID_PASSWORD,
                            type=MessageTypes.ERROR,
                            body='Invalid password.', )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_function)
    ]
